apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: example-nvidia-nim-llama2-7b-chat
spec:
  predictor:
    nodeSelector:
      k8s.amazonaws.com/accelerator: "nvidia-tesla-t4"
    model:
      modelFormat:
        name: llm-nvidia-nim 
      storageUri: "pvc://task-pv-claim/model-store"
      runtime: kserve-llm-nvidia-nim
      resources:
        limits:
          nvidia.com/gpu: 1
        requests:
          nvidia.com/gpu: 1

